global:
  scrape_interval: 5s

scrape_configs:
  - job_name: gateway
    metrics_path: /metrics
    static_configs:
      - targets: ['gateway:8000']

  - job_name: anomaly-detector
    metrics_path: /metrics
    static_configs:
      - targets: ['anomaly-detector:9000']

